# Define the GitLab CI/CD pipeline stages
stages:
  - build
  - test

# Define job to build the C/C++ project
build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

# Define job to run tests
test:
  stage: test
  script:
    - cd build
    - ctest
